namespace Challenges.Extractors
{
    public static class Registry
    {
        public static IReadOnlyList<IExtractor> All { get; } =
        [
            new AchievementEarned(),
            new AddPlayerSonarIcon(),
            new AmmoPickup(),
            new BombAbortdefuse(),
            new BombAbortplant(),
            new BombBeep(),
            new BombBegindefuse(),
            new BombBeginplant(),
            new BombDefused(),
            new BombDropped(),
            new BombExploded(),
            new BombPickup(),
            new BombPlanted(),
            new BotTakeover(),
            new BreakBreakable(),
            new BreakProp(),
            new BulletDamage(),
            new BulletImpact(),
            new BuymenuClose(),
            new BuytimeEnded(),
            new DefuserPickup(),
            new DoorClosed(),
            new DoorOpen(),
            new EnterBombzone(),
            new EnterBuyzone(),
            new EnterRescuezone(),
            new ExitBombzone(),
            new ExitBuyzone(),
            new ExitRescuezone(),
            new GrenadeBounce(),
            new GrenadeThrown(),
            new HostageFollows(),
            new HostageHurt(),
            new HostageKilled(),
            new HostageRescuedAll(),
            new HostageRescued(),
            new HostageStopsFollowing(),
            new InspectWeapon(),
            new ItemPickup(),
            new ItemPurchase(),
            new PlayerAvengedTeammate(),
            new PlayerBlind(),
            new PlayerChangename(),
            new PlayerChat(),
            new PlayerDeath(),
            new PlayerDecal(),
            new PlayerFalldamage(),
            new PlayerFootstep(),
            new PlayerGivenC4(),
            new PlayerHurt(),
            new PlayerJump(),
            new PlayerPing(),
            new PlayerRadio(),
            new PlayerScore(),
            new PlayerSound(),
            new PlayerSpawned(),
            new PlayerTeam(),
            new TeamScore(),
            new WeaponFire(),
            new WeaponFireOnEmpty(),
            new WeaponReload(),
            new WeaponZoom(),
            new WeaponZoomRifle()
        ];
    }
}
