/** Generated by tools/hud_themes.py — do not edit. */
window.HUD_THEMES = {
  red: { accent: '#e05a5a', from: '#a83a3a', to: '#e05a5a' },
  coral: { accent: '#ff7a59', from: '#c44830', to: '#ff7a59' },
  orange: { accent: '#ff8a3d', from: '#c45a1a', to: '#ff8a3d' },
  copper: { accent: '#e08a5a', from: '#a85a30', to: '#e08a5a' },
  gold: { accent: '#f0a531', from: '#f0a531', to: '#ffd27a' },
  t: { accent: '#eabe54', from: '#c9a03a', to: '#eabe54' },
  lime: { accent: '#c6f04a', from: '#7aa81a', to: '#c6f04a' },
  green: { accent: '#6fdc78', from: '#3d8f45', to: '#6fdc78' },
  teal: { accent: '#2ec9a6', from: '#17856c', to: '#2ec9a6' },
  cyan: { accent: '#3ee0f0', from: '#1a9bb0', to: '#3ee0f0' },
  blue: { accent: '#5b8cff', from: '#2d56c4', to: '#5b8cff' },
  ct: { accent: '#96c8fa', from: '#5a9fd4', to: '#96c8fa' },
  purple: { accent: '#b07cff', from: '#7a4fc4', to: '#b07cff' },
  magenta: { accent: '#e85dff', from: '#a030c0', to: '#e85dff' },
  pink: { accent: '#ff6b9a', from: '#c43a68', to: '#ff6b9a' },
  silver: { accent: '#c9d2dc', from: '#8a96a6', to: '#c9d2dc' },
};
