// <auto-generated> one forwarder per Registry event class; regenerate when an extractor is added.
using CounterStrikeSharp.API.Core;
using CounterStrikeSharp.API.Modules.Events;

namespace Challenges.Classes
{
    public partial class ChallengeEngine
    {
        public HookResult EventAchievementEarned(EventAchievementEarned @event, GameEventInfo info) => HandleEvent("EventAchievementEarned", @event);
        public HookResult EventAddPlayerSonarIcon(EventAddPlayerSonarIcon @event, GameEventInfo info) => HandleEvent("EventAddPlayerSonarIcon", @event);
        public HookResult EventAmmoPickup(EventAmmoPickup @event, GameEventInfo info) => HandleEvent("EventAmmoPickup", @event);
        public HookResult EventBombAbortdefuse(EventBombAbortdefuse @event, GameEventInfo info) => HandleEvent("EventBombAbortdefuse", @event);
        public HookResult EventBombAbortplant(EventBombAbortplant @event, GameEventInfo info) => HandleEvent("EventBombAbortplant", @event);
        public HookResult EventBombBeep(EventBombBeep @event, GameEventInfo info) => HandleEvent("EventBombBeep", @event);
        public HookResult EventBombBegindefuse(EventBombBegindefuse @event, GameEventInfo info) => HandleEvent("EventBombBegindefuse", @event);
        public HookResult EventBombBeginplant(EventBombBeginplant @event, GameEventInfo info) => HandleEvent("EventBombBeginplant", @event);
        public HookResult EventBombDefused(EventBombDefused @event, GameEventInfo info) => HandleEvent("EventBombDefused", @event);
        public HookResult EventBombDropped(EventBombDropped @event, GameEventInfo info) => HandleEvent("EventBombDropped", @event);
        public HookResult EventBombExploded(EventBombExploded @event, GameEventInfo info) => HandleEvent("EventBombExploded", @event);
        public HookResult EventBombPickup(EventBombPickup @event, GameEventInfo info) => HandleEvent("EventBombPickup", @event);
        public HookResult EventBombPlanted(EventBombPlanted @event, GameEventInfo info) => HandleEvent("EventBombPlanted", @event);
        public HookResult EventBotTakeover(EventBotTakeover @event, GameEventInfo info) => HandleEvent("EventBotTakeover", @event);
        public HookResult EventBreakBreakable(EventBreakBreakable @event, GameEventInfo info) => HandleEvent("EventBreakBreakable", @event);
        public HookResult EventBreakProp(EventBreakProp @event, GameEventInfo info) => HandleEvent("EventBreakProp", @event);
        public HookResult EventBulletDamage(EventBulletDamage @event, GameEventInfo info) => HandleEvent("EventBulletDamage", @event);
        public HookResult EventBulletImpact(EventBulletImpact @event, GameEventInfo info) => HandleEvent("EventBulletImpact", @event);
        public HookResult EventBuymenuClose(EventBuymenuClose @event, GameEventInfo info) => HandleEvent("EventBuymenuClose", @event);
        public HookResult EventBuytimeEnded(EventBuytimeEnded @event, GameEventInfo info) => HandleEvent("EventBuytimeEnded", @event);
        public HookResult EventDefuserPickup(EventDefuserPickup @event, GameEventInfo info) => HandleEvent("EventDefuserPickup", @event);
        public HookResult EventDoorClosed(EventDoorClosed @event, GameEventInfo info) => HandleEvent("EventDoorClosed", @event);
        public HookResult EventDoorOpen(EventDoorOpen @event, GameEventInfo info) => HandleEvent("EventDoorOpen", @event);
        public HookResult EventEnterBombzone(EventEnterBombzone @event, GameEventInfo info) => HandleEvent("EventEnterBombzone", @event);
        public HookResult EventEnterBuyzone(EventEnterBuyzone @event, GameEventInfo info) => HandleEvent("EventEnterBuyzone", @event);
        public HookResult EventEnterRescueZone(EventEnterRescueZone @event, GameEventInfo info) => HandleEvent("EventEnterRescueZone", @event);
        public HookResult EventExitBombzone(EventExitBombzone @event, GameEventInfo info) => HandleEvent("EventExitBombzone", @event);
        public HookResult EventExitBuyzone(EventExitBuyzone @event, GameEventInfo info) => HandleEvent("EventExitBuyzone", @event);
        public HookResult EventExitRescueZone(EventExitRescueZone @event, GameEventInfo info) => HandleEvent("EventExitRescueZone", @event);
        public HookResult EventGrenadeBounce(EventGrenadeBounce @event, GameEventInfo info) => HandleEvent("EventGrenadeBounce", @event);
        public HookResult EventGrenadeThrown(EventGrenadeThrown @event, GameEventInfo info) => HandleEvent("EventGrenadeThrown", @event);
        public HookResult EventHostageFollows(EventHostageFollows @event, GameEventInfo info) => HandleEvent("EventHostageFollows", @event);
        public HookResult EventHostageHurt(EventHostageHurt @event, GameEventInfo info) => HandleEvent("EventHostageHurt", @event);
        public HookResult EventHostageKilled(EventHostageKilled @event, GameEventInfo info) => HandleEvent("EventHostageKilled", @event);
        public HookResult EventHostageRescued(EventHostageRescued @event, GameEventInfo info) => HandleEvent("EventHostageRescued", @event);
        public HookResult EventHostageRescuedAll(EventHostageRescuedAll @event, GameEventInfo info) => HandleEvent("EventHostageRescuedAll", @event);
        public HookResult EventHostageStopsFollowing(EventHostageStopsFollowing @event, GameEventInfo info) => HandleEvent("EventHostageStopsFollowing", @event);
        public HookResult EventInspectWeapon(EventInspectWeapon @event, GameEventInfo info) => HandleEvent("EventInspectWeapon", @event);
        public HookResult EventItemPickup(EventItemPickup @event, GameEventInfo info) => HandleEvent("EventItemPickup", @event);
        public HookResult EventItemPurchase(EventItemPurchase @event, GameEventInfo info) => HandleEvent("EventItemPurchase", @event);
        public HookResult EventPlayerAvengedTeammate(EventPlayerAvengedTeammate @event, GameEventInfo info) => HandleEvent("EventPlayerAvengedTeammate", @event);
        public HookResult EventPlayerBlind(EventPlayerBlind @event, GameEventInfo info) => HandleEvent("EventPlayerBlind", @event);
        public HookResult EventPlayerChangename(EventPlayerChangename @event, GameEventInfo info) => HandleEvent("EventPlayerChangename", @event);
        public HookResult EventPlayerChat(EventPlayerChat @event, GameEventInfo info) => HandleEvent("EventPlayerChat", @event);
        public HookResult EventPlayerDeath(EventPlayerDeath @event, GameEventInfo info) => HandleEvent("EventPlayerDeath", @event);
        public HookResult EventPlayerDecal(EventPlayerDecal @event, GameEventInfo info) => HandleEvent("EventPlayerDecal", @event);
        public HookResult EventPlayerFalldamage(EventPlayerFalldamage @event, GameEventInfo info) => HandleEvent("EventPlayerFalldamage", @event);
        public HookResult EventPlayerFootstep(EventPlayerFootstep @event, GameEventInfo info) => HandleEvent("EventPlayerFootstep", @event);
        public HookResult EventPlayerGivenC4(EventPlayerGivenC4 @event, GameEventInfo info) => HandleEvent("EventPlayerGivenC4", @event);
        public HookResult EventPlayerHurt(EventPlayerHurt @event, GameEventInfo info) => HandleEvent("EventPlayerHurt", @event);
        public HookResult EventPlayerJump(EventPlayerJump @event, GameEventInfo info) => HandleEvent("EventPlayerJump", @event);
        public HookResult EventPlayerPing(EventPlayerPing @event, GameEventInfo info) => HandleEvent("EventPlayerPing", @event);
        public HookResult EventPlayerRadio(EventPlayerRadio @event, GameEventInfo info) => HandleEvent("EventPlayerRadio", @event);
        public HookResult EventPlayerScore(EventPlayerScore @event, GameEventInfo info) => HandleEvent("EventPlayerScore", @event);
        public HookResult EventPlayerSound(EventPlayerSound @event, GameEventInfo info) => HandleEvent("EventPlayerSound", @event);
        public HookResult EventPlayerSpawned(EventPlayerSpawned @event, GameEventInfo info) => HandleEvent("EventPlayerSpawned", @event);
        public HookResult EventPlayerTeam(EventPlayerTeam @event, GameEventInfo info) => HandleEvent("EventPlayerTeam", @event);
        public HookResult EventTeamScore(EventTeamScore @event, GameEventInfo info) => HandleEvent("EventTeamScore", @event);
        public HookResult EventWeaponFire(EventWeaponFire @event, GameEventInfo info) => HandleEvent("EventWeaponFire", @event);
        public HookResult EventWeaponFireOnEmpty(EventWeaponFireOnEmpty @event, GameEventInfo info) => HandleEvent("EventWeaponFireOnEmpty", @event);
        public HookResult EventWeaponReload(EventWeaponReload @event, GameEventInfo info) => HandleEvent("EventWeaponReload", @event);
        public HookResult EventWeaponZoom(EventWeaponZoom @event, GameEventInfo info) => HandleEvent("EventWeaponZoom", @event);
        public HookResult EventWeaponZoomRifle(EventWeaponZoomRifle @event, GameEventInfo info) => HandleEvent("EventWeaponZoomRifle", @event);
    }
}
