// <auto-generated> by tools/generate_events.py — do not edit.
#nullable enable
using CounterStrikeSharp.API;
using CounterStrikeSharp.API.Core;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Utils;
using Challenges.Utils;

namespace Challenges.Classes
{
    public partial class ChallengeEngine
    {
        public void OnEntitySpawned(CEntityInstance entity)
        {
            Dictionary<string, string> d = [];
            d["entity.designername"] = entity.DesignerName;
            d["entity.index"] = EventData.Num(entity.Index);
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_entity_spawned"));
            }
            HandleListener("OnEntitySpawned", d, targets);
        }

        public void OnEntityCreated(CEntityInstance entity)
        {
            Dictionary<string, string> d = [];
            d["entity.designername"] = entity.DesignerName;
            d["entity.index"] = EventData.Num(entity.Index);
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_entity_created"));
            }
            HandleListener("OnEntityCreated", d, targets);
        }

        public void OnEntityDeleted(CEntityInstance entity)
        {
            Dictionary<string, string> d = [];
            d["entity.designername"] = entity.DesignerName;
            d["entity.index"] = EventData.Num(entity.Index);
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_entity_deleted"));
            }
            HandleListener("OnEntityDeleted", d, targets);
        }

        public void OnEntityParentChanged(CEntityInstance entity, CEntityInstance newParent)
        {
            Dictionary<string, string> d = [];
            d["entity.designername"] = entity.DesignerName;
            d["entity.index"] = EventData.Num(entity.Index);
            d["newParent.designername"] = newParent.DesignerName;
            d["newParent.index"] = EventData.Num(newParent.Index);
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_entity_parent_changed"));
            }
            HandleListener("OnEntityParentChanged", d, targets);
        }

        public HookResult OnEntityTakeDamagePre(CBaseEntity entity, CTakeDamageInfo info)
        {
            Dictionary<string, string> d = [];
            d["entity.designername"] = entity.DesignerName;
            d["entity.index"] = EventData.Num(entity.Index);
            d["damage.damage"] = EventData.Num(info.Damage);
            d["damage.totalled_damage"] = EventData.Num(info.TotalledDamage);
            d["damage.bits_damage_type"] = info.BitsDamageType.ToString();
            d["damage.damage_custom"] = EventData.Num(info.DamageCustom);
            d["damage.ammo_type"] = EventData.Num(info.AmmoType);
            d["damage.original_damage"] = EventData.Num(info.OriginalDamage);
            d["damage.should_bleed"] = EventData.Bool(info.ShouldBleed);
            d["damage.should_spark"] = EventData.Bool(info.ShouldSpark);
            d["damage.damage_flags"] = info.DamageFlags.ToString();
            d["damage.hit_group_id"] = info.HitGroupId.ToString();
            d["damage.num_objects_penetrated"] = EventData.Num(info.NumObjectsPenetrated);
            d["damage.friendly_fire_damage_reduction_ratio"] = EventData.Num(info.FriendlyFireDamageReductionRatio);
            d["damage.stopped_bullet"] = EventData.Bool(info.StoppedBullet);
            d["damage.in_take_damage_flow"] = EventData.Bool(info.InTakeDamageFlow);
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_entity_take_damage_pre"));
            }
            HandleListener("OnEntityTakeDamagePre", d, targets);
            return HookResult.Continue;
        }

        public void OnEntityTakeDamagePost(CBaseEntity entity, CTakeDamageInfo info, CTakeDamageResult result)
        {
            Dictionary<string, string> d = [];
            d["entity.designername"] = entity.DesignerName;
            d["entity.index"] = EventData.Num(entity.Index);
            d["damage.damage"] = EventData.Num(info.Damage);
            d["damage.totalled_damage"] = EventData.Num(info.TotalledDamage);
            d["damage.bits_damage_type"] = info.BitsDamageType.ToString();
            d["damage.damage_custom"] = EventData.Num(info.DamageCustom);
            d["damage.ammo_type"] = EventData.Num(info.AmmoType);
            d["damage.original_damage"] = EventData.Num(info.OriginalDamage);
            d["damage.should_bleed"] = EventData.Bool(info.ShouldBleed);
            d["damage.should_spark"] = EventData.Bool(info.ShouldSpark);
            d["damage.damage_flags"] = info.DamageFlags.ToString();
            d["damage.hit_group_id"] = info.HitGroupId.ToString();
            d["damage.num_objects_penetrated"] = EventData.Num(info.NumObjectsPenetrated);
            d["damage.friendly_fire_damage_reduction_ratio"] = EventData.Num(info.FriendlyFireDamageReductionRatio);
            d["damage.stopped_bullet"] = EventData.Bool(info.StoppedBullet);
            d["damage.in_take_damage_flow"] = EventData.Bool(info.InTakeDamageFlow);
            d["result.health_lost"] = EventData.Num(result.HealthLost);
            d["result.health_before"] = EventData.Num(result.HealthBefore);
            d["result.damage_dealt"] = EventData.Num(result.DamageDealt);
            d["result.pre_modified_damage"] = EventData.Num(result.PreModifiedDamage);
            d["result.totalled_health_lost"] = EventData.Num(result.TotalledHealthLost);
            d["result.totalled_damage_dealt"] = EventData.Num(result.TotalledDamageDealt);
            d["result.totalled_pre_modified_damage"] = EventData.Num(result.TotalledPreModifiedDamage);
            d["result.new_damage_accumulator_value"] = EventData.Num(result.NewDamageAccumulatorValue);
            d["result.damage_flags"] = result.DamageFlags.ToString();
            d["result.was_damage_suppressed"] = EventData.Bool(result.WasDamageSuppressed);
            d["result.suppress_flinch"] = EventData.Bool(result.SuppressFlinch);
            d["result.override_flinch_hit_group"] = result.OverrideFlinchHitGroup.ToString();
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_entity_take_damage_post"));
            }
            HandleListener("OnEntityTakeDamagePost", d, targets);
        }

        public HookResult OnPlayerTakeDamagePre(CCSPlayerPawn player, CTakeDamageInfo info)
        {
            Dictionary<string, string> d = [];
            CCSPlayerController? playerController = player.OriginalController?.Value;
            EventData.FillPlayer(d, playerController, "player");
            d["damage.damage"] = EventData.Num(info.Damage);
            d["damage.totalled_damage"] = EventData.Num(info.TotalledDamage);
            d["damage.bits_damage_type"] = info.BitsDamageType.ToString();
            d["damage.damage_custom"] = EventData.Num(info.DamageCustom);
            d["damage.ammo_type"] = EventData.Num(info.AmmoType);
            d["damage.original_damage"] = EventData.Num(info.OriginalDamage);
            d["damage.should_bleed"] = EventData.Bool(info.ShouldBleed);
            d["damage.should_spark"] = EventData.Bool(info.ShouldSpark);
            d["damage.damage_flags"] = info.DamageFlags.ToString();
            d["damage.hit_group_id"] = info.HitGroupId.ToString();
            d["damage.num_objects_penetrated"] = EventData.Num(info.NumObjectsPenetrated);
            d["damage.friendly_fire_damage_reduction_ratio"] = EventData.Num(info.FriendlyFireDamageReductionRatio);
            d["damage.stopped_bullet"] = EventData.Bool(info.StoppedBullet);
            d["damage.in_take_damage_flow"] = EventData.Bool(info.InTakeDamageFlow);
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = playerController;
            targets.Add((targetPlayer, "on_player_take_damage_pre"));
            HandleListener("OnPlayerTakeDamagePre", d, targets);
            return HookResult.Continue;
        }

        public void OnPlayerTakeDamagePost(CCSPlayerPawn player, CTakeDamageInfo info, CTakeDamageResult result)
        {
            Dictionary<string, string> d = [];
            CCSPlayerController? playerController = player.OriginalController?.Value;
            EventData.FillPlayer(d, playerController, "player");
            d["damage.damage"] = EventData.Num(info.Damage);
            d["damage.totalled_damage"] = EventData.Num(info.TotalledDamage);
            d["damage.bits_damage_type"] = info.BitsDamageType.ToString();
            d["damage.damage_custom"] = EventData.Num(info.DamageCustom);
            d["damage.ammo_type"] = EventData.Num(info.AmmoType);
            d["damage.original_damage"] = EventData.Num(info.OriginalDamage);
            d["damage.should_bleed"] = EventData.Bool(info.ShouldBleed);
            d["damage.should_spark"] = EventData.Bool(info.ShouldSpark);
            d["damage.damage_flags"] = info.DamageFlags.ToString();
            d["damage.hit_group_id"] = info.HitGroupId.ToString();
            d["damage.num_objects_penetrated"] = EventData.Num(info.NumObjectsPenetrated);
            d["damage.friendly_fire_damage_reduction_ratio"] = EventData.Num(info.FriendlyFireDamageReductionRatio);
            d["damage.stopped_bullet"] = EventData.Bool(info.StoppedBullet);
            d["damage.in_take_damage_flow"] = EventData.Bool(info.InTakeDamageFlow);
            d["result.health_lost"] = EventData.Num(result.HealthLost);
            d["result.health_before"] = EventData.Num(result.HealthBefore);
            d["result.damage_dealt"] = EventData.Num(result.DamageDealt);
            d["result.pre_modified_damage"] = EventData.Num(result.PreModifiedDamage);
            d["result.totalled_health_lost"] = EventData.Num(result.TotalledHealthLost);
            d["result.totalled_damage_dealt"] = EventData.Num(result.TotalledDamageDealt);
            d["result.totalled_pre_modified_damage"] = EventData.Num(result.TotalledPreModifiedDamage);
            d["result.new_damage_accumulator_value"] = EventData.Num(result.NewDamageAccumulatorValue);
            d["result.damage_flags"] = result.DamageFlags.ToString();
            d["result.was_damage_suppressed"] = EventData.Bool(result.WasDamageSuppressed);
            d["result.suppress_flinch"] = EventData.Bool(result.SuppressFlinch);
            d["result.override_flinch_hit_group"] = result.OverrideFlinchHitGroup.ToString();
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = playerController;
            targets.Add((targetPlayer, "on_player_take_damage_post"));
            HandleListener("OnPlayerTakeDamagePost", d, targets);
        }

        public void OnMapStart(string mapName)
        {
            Dictionary<string, string> d = [];
            d["mapname"] = mapName;
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_map_start"));
            }
            HandleListener("OnMapStart", d, targets);
        }

        public void OnMapEnd()
        {
            Dictionary<string, string> d = [];
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_map_end"));
            }
            HandleListener("OnMapEnd", d, targets);
        }

        public void OnClientConnect(int playerSlot, string name, string ipAddress)
        {
            Dictionary<string, string> d = [];
            CCSPlayerController? playerSlotPlayer = Utilities.GetPlayerFromSlot(playerSlot);
            EventData.FillPlayer(d, playerSlotPlayer, "player");
            d["name"] = name;
            d["ipaddress"] = ipAddress;
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = playerSlotPlayer;
            targets.Add((targetPlayer, "on_client_connect"));
            HandleListener("OnClientConnect", d, targets);
        }

        public void OnClientConnected(int playerSlot)
        {
            Dictionary<string, string> d = [];
            CCSPlayerController? playerSlotPlayer = Utilities.GetPlayerFromSlot(playerSlot);
            EventData.FillPlayer(d, playerSlotPlayer, "player");
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = playerSlotPlayer;
            targets.Add((targetPlayer, "on_client_connected"));
            HandleListener("OnClientConnected", d, targets);
        }

        public void OnClientPutInServer(int playerSlot)
        {
            Dictionary<string, string> d = [];
            CCSPlayerController? playerSlotPlayer = Utilities.GetPlayerFromSlot(playerSlot);
            EventData.FillPlayer(d, playerSlotPlayer, "player");
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = playerSlotPlayer;
            targets.Add((targetPlayer, "on_client_put_in_server"));
            HandleListener("OnClientPutInServer", d, targets);
        }

        public void OnClientDisconnect(int playerSlot)
        {
            Dictionary<string, string> d = [];
            CCSPlayerController? playerSlotPlayer = Utilities.GetPlayerFromSlot(playerSlot);
            EventData.FillPlayer(d, playerSlotPlayer, "player");
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = playerSlotPlayer;
            targets.Add((targetPlayer, "on_client_disconnect"));
            HandleListener("OnClientDisconnect", d, targets);
        }

        public void OnClientDisconnectPost(int playerSlot)
        {
            Dictionary<string, string> d = [];
            CCSPlayerController? playerSlotPlayer = Utilities.GetPlayerFromSlot(playerSlot);
            EventData.FillPlayer(d, playerSlotPlayer, "player");
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = playerSlotPlayer;
            targets.Add((targetPlayer, "on_client_disconnect_post"));
            HandleListener("OnClientDisconnectPost", d, targets);
        }

        public void OnClientVoice(int playerSlot)
        {
            Dictionary<string, string> d = [];
            CCSPlayerController? playerSlotPlayer = Utilities.GetPlayerFromSlot(playerSlot);
            EventData.FillPlayer(d, playerSlotPlayer, "player");
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = playerSlotPlayer;
            targets.Add((targetPlayer, "on_client_voice"));
            HandleListener("OnClientVoice", d, targets);
        }

        public void OnClientAuthorized(int playerSlot, SteamID steamId)
        {
            Dictionary<string, string> d = [];
            CCSPlayerController? playerSlotPlayer = Utilities.GetPlayerFromSlot(playerSlot);
            EventData.FillPlayer(d, playerSlotPlayer, "player");
            d["steamid"] = steamId.SteamId64.ToString();
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = playerSlotPlayer;
            targets.Add((targetPlayer, "on_client_authorized"));
            HandleListener("OnClientAuthorized", d, targets);
        }

        public void OnServerHibernationUpdate(bool isHibernating)
        {
            Dictionary<string, string> d = [];
            d["ishibernating"] = EventData.Bool(isHibernating);
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_server_hibernation_update"));
            }
            HandleListener("OnServerHibernationUpdate", d, targets);
        }

        public void OnGameServerSteamAPIActivated()
        {
            Dictionary<string, string> d = [];
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_game_server_steam_api_activated"));
            }
            HandleListener("OnGameServerSteamAPIActivated", d, targets);
        }

        public void OnGameServerSteamAPIDeactivated()
        {
            Dictionary<string, string> d = [];
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_game_server_steam_api_deactivated"));
            }
            HandleListener("OnGameServerSteamAPIDeactivated", d, targets);
        }

        public void OnHostNameChanged(string hostname)
        {
            Dictionary<string, string> d = [];
            d["hostname"] = hostname;
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_host_name_changed"));
            }
            HandleListener("OnHostNameChanged", d, targets);
        }

        public void OnServerPreFatalShutdown()
        {
            Dictionary<string, string> d = [];
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_server_pre_fatal_shutdown"));
            }
            HandleListener("OnServerPreFatalShutdown", d, targets);
        }

        public void OnServerPrecacheResources(ResourceManifest manifest)
        {
            Dictionary<string, string> d = [];
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_server_precache_resources"));
            }
            HandleListener("OnServerPrecacheResources", d, targets);
        }

        public void OnPlayerButtonsChanged(CCSPlayerController player, PlayerButtons pressed, PlayerButtons released)
        {
            Dictionary<string, string> d = [];
            EventData.FillPlayer(d, player, "player");
            d["pressed"] = EventData.Num((ulong)pressed);
            d["released"] = EventData.Num((ulong)released);
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = player;
            targets.Add((targetPlayer, "on_player_buttons_changed"));
            HandleListener("OnPlayerButtonsChanged", d, targets);
        }

        public void OnPlayerChat(CCSPlayerController player, string message, bool teamChat)
        {
            Dictionary<string, string> d = [];
            EventData.FillPlayer(d, player, "player");
            d["message"] = message;
            d["text"] = d["message"];
            d["teamchat"] = EventData.Bool(teamChat);
            d["teamonly"] = d["teamchat"];
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = player;
            targets.Add((targetPlayer, "on_player_chat"));
            targets.Add((targetPlayer, "player_chat"));
            HandleListener("OnPlayerChat", d, targets);
        }

        public void OnMetamodAllPluginsLoaded()
        {
            Dictionary<string, string> d = [];
            List<(CCSPlayerController? Player, string Type)> targets = [];
            foreach (var entry in Utilities.GetPlayers())
            {
                targets.Add((entry, "on_metamod_all_plugins_loaded"));
            }
            HandleListener("OnMetamodAllPluginsLoaded", d, targets);
        }

        public void OnCustomHudClicked(CCSPlayerController player, CCSCustomHudLayout customLayout, string buttonId)
        {
            Dictionary<string, string> d = [];
            EventData.FillPlayer(d, player, "player");
            d["buttonid"] = buttonId;
            List<(CCSPlayerController? Player, string Type)> targets = [];
            CCSPlayerController? targetPlayer = player;
            targets.Add((targetPlayer, "on_custom_hud_clicked"));
            HandleListener("OnCustomHudClicked", d, targets);
        }

    }
}
