"""Single source of truth for gui.theme accent palettes.

Used by validate_panorama.py to emit hud.vcss theme rules and preview/theme-data.js.
"""
from __future__ import annotations

from pathlib import Path

# name, accent, gradient_from, gradient_to — rainbow order (warm → cool), silver last.
THEMES: list[tuple[str, str, str, str]] = [
    ("red", "#e05a5a", "#a83a3a", "#e05a5a"),
    ("coral", "#ff7a59", "#c44830", "#ff7a59"),
    ("orange", "#ff8a3d", "#c45a1a", "#ff8a3d"),
    ("copper", "#e08a5a", "#a85a30", "#e08a5a"),
    ("gold", "#f0a531", "#f0a531", "#ffd27a"),
    ("t", "#eabe54", "#c9a03a", "#eabe54"),
    ("lime", "#c6f04a", "#7aa81a", "#c6f04a"),
    ("green", "#6fdc78", "#3d8f45", "#6fdc78"),
    ("teal", "#2ec9a6", "#17856c", "#2ec9a6"),
    ("cyan", "#3ee0f0", "#1a9bb0", "#3ee0f0"),
    ("blue", "#5b8cff", "#2d56c4", "#5b8cff"),
    ("ct", "#96c8fa", "#5a9fd4", "#96c8fa"),
    ("purple", "#b07cff", "#7a4fc4", "#b07cff"),
    ("magenta", "#e85dff", "#a030c0", "#e85dff"),
    ("pink", "#ff6b9a", "#c43a68", "#ff6b9a"),
    ("silver", "#c9d2dc", "#8a96a6", "#c9d2dc"),
]

BEGIN = "/* >>> hud_themes:begin */"
END = "/* <<< hud_themes:end */"

LABEL_SELECTORS = """\
.{cls} Label.ph-stat-val,
.{cls} Label.ScoreSelfRank,
.{cls} Label.ScoreSelfStatVal,
.{cls} Label.ScoreRank,
.{cls} Label.ScoreCur,
.{cls} Label.ScoreTitlePage,
.{cls} Label.ScoreHead.sort-active,
.{cls} .ScoreHeader Label.ScoreCur.sort-active,
.{cls} .ScoreHeader Label.ScoreTot.sort-active
{{ color: {accent}; }}
"""

OVERRIDE_RULES = """\
.{cls} .MenuFilterBtn.active {{ background-color: {a}22; border: 1px solid {accent}; }}
.{cls} .MenuFilterBtn.active:hover {{ background-color: {a}44; border: 1px solid {accent}; }}
.{cls} .MenuFilterBtn:hover {{ border: 1px solid {a}66; }}
.{cls} .MenuFilterBtn:active {{ border: 1px solid {accent}; }}
.{cls} .MenuTitleNav:hover {{ border: 1px solid {a}66; }}
.{cls} .MenuTitleNav:active {{ border: 1px solid {accent}; }}
.{cls} .MenuRow:hover {{ border: 1px solid {a}66; }}
.{cls} .MenuRow:active {{ border: 1px solid {accent}; }}
.{cls} .MenuRow.is-selected {{ background-color: {a}22; border: 1px solid {accent}; }}
.{cls} .MenuRow.is-selected:hover {{ background-color: {a}44; border: 1px solid {accent}; }}
.{cls} .ScoreSelfCard {{ background-color: {a}18; border: 1px solid {accent}; }}
.{cls} .ScoreRow:hover {{ border: 1px solid {a}66; border-bottom: 1px solid {a}66; }}
.{cls} .ScoreRow:active {{ border: 1px solid {accent}; border-bottom: 1px solid {accent}; }}
.{cls} .ScoreRow.is-self {{ background-color: {a}22; border-bottom: 1px solid {a}44; }}
.{cls} .ScoreRow.is-viewing {{ background-color: {a}22; border: 1px solid {accent}; border-bottom: 1px solid {accent}; }}
.{cls} .ScoreRow.is-viewing:hover {{ background-color: {a}44; border: 1px solid {accent}; border-bottom: 1px solid {accent}; }}
.{cls} .ScoreHeader {{ border-top: 1px solid {a}66; border-bottom: 1px solid {a}66; }}
.{cls} .MenuTask.is-done .MenuTaskMark {{ background-color: {accent}; }}
"""


def names() -> list[str]:
    return [name for name, *_ in THEMES]


def class_names() -> list[str]:
    return [f"theme-{name}" for name in names()]


def render_panorama_css() -> str:
    chunks = [
        BEGIN,
        "/* Accent themes (gui.theme). Generated from tools/hud_themes.py — do not edit by hand. */",
        "/* Gold is the baked-in default; other themes override accents. CT/T = stock CS2 colours. */",
        "",
    ]
    for name, accent, grad_from, grad_to in THEMES:
        cls = f"theme-{name}"
        chunks.append(f".{cls} .ph-bar {{ background-color: {accent}; }}")
        chunks.append(
            f".{cls} .ph-stat-fill {{ background-color: gradient( linear, 0% 0%, 100% 0%, "
            f"from( {grad_from} ), to( {grad_to} ) ); }}"
        )
        if name != "gold":
            chunks.append(LABEL_SELECTORS.format(cls=cls, accent=accent).rstrip())
            chunks.append(OVERRIDE_RULES.format(cls=cls, accent=accent, a=accent).rstrip())
        chunks.append("")
    chunks.append(END)
    return "\n".join(chunks).rstrip() + "\n"


def render_theme_data_js() -> str:
    lines = [
        "/** Generated by tools/hud_themes.py — do not edit. */",
        "window.HUD_THEMES = {",
    ]
    for name, accent, grad_from, grad_to in THEMES:
        lines.append(
            f"  {name}: {{ accent: '{accent}', from: '{grad_from}', to: '{grad_to}' }},"
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def sync_file(path: Path, expected: str) -> bool:
    """Write expected content if missing or different. Returns True when written."""
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == expected:
        return False
    path.write_text(expected, encoding="utf-8")
    return True


def sync_vcss_section(vcss_path: Path) -> bool:
    text = vcss_path.read_text(encoding="utf-8")
    generated = render_panorama_css()
    if BEGIN in text and END in text:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        # Keep a single trailing newline after the section.
        after = text[end:].lstrip("\n")
        before = text[:start].rstrip() + "\n\n"
        new_text = before + generated + (("\n" + after) if after else "")
    else:
        # Replace legacy accent-theme tail starting at the first theme comment / .theme-gold.
        marker = "/* ============================================================================\n   Accent themes"
        idx = text.find(marker)
        if idx < 0:
            idx = text.find(".theme-gold .ph-bar")
        if idx < 0:
            new_text = text.rstrip() + "\n\n" + generated
        else:
            new_text = text[:idx].rstrip() + "\n\n" + generated
    if new_text == text:
        return False
    vcss_path.write_text(new_text, encoding="utf-8")
    return True
